// Mocks generated by Mockito 5.4.6 from annotations
// in llm_chat_app/test/settings_sync_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;
import 'dart:ui' as _i8;

import 'package:llm_chat_app/models/flashcard_session.dart' as _i3;
import 'package:llm_chat_app/models/user.dart' as _i6;
import 'package:llm_chat_app/models/user_vocabulary.dart' as _i7;
import 'package:llm_chat_app/services/auth_service.dart' as _i2;
import 'package:llm_chat_app/services/user_service.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeAuthResult_0 extends _i1.SmartFake implements _i2.AuthResult {
  _FakeAuthResult_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeFlashcardSession_1 extends _i1.SmartFake
    implements _i3.FlashcardSession {
  _FakeFlashcardSession_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeFlashcardSessionCard_2 extends _i1.SmartFake
    implements _i3.FlashcardSessionCard {
  _FakeFlashcardSessionCard_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [UserService].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserService extends _i1.Mock implements _i4.UserService {
  MockUserService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isLoading => (super.noSuchMethod(
        Invocation.getter(#isLoading),
        returnValue: false,
      ) as bool);

  @override
  bool get isLoggedIn => (super.noSuchMethod(
        Invocation.getter(#isLoggedIn),
        returnValue: false,
      ) as bool);

  @override
  bool get isPremium => (super.noSuchMethod(
        Invocation.getter(#isPremium),
        returnValue: false,
      ) as bool);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  _i5.Future<_i2.AuthResult> signIn(
    String? email,
    String? password,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #signIn,
          [
            email,
            password,
          ],
        ),
        returnValue: _i5.Future<_i2.AuthResult>.value(_FakeAuthResult_0(
          this,
          Invocation.method(
            #signIn,
            [
              email,
              password,
            ],
          ),
        )),
      ) as _i5.Future<_i2.AuthResult>);

  @override
  _i5.Future<_i2.AuthResult> signUp(
    String? email,
    String? password,
    String? firstName,
    String? lastName,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #signUp,
          [
            email,
            password,
            firstName,
            lastName,
          ],
        ),
        returnValue: _i5.Future<_i2.AuthResult>.value(_FakeAuthResult_0(
          this,
          Invocation.method(
            #signUp,
            [
              email,
              password,
              firstName,
              lastName,
            ],
          ),
        )),
      ) as _i5.Future<_i2.AuthResult>);

  @override
  _i5.Future<void> signOut() => (super.noSuchMethod(
        Invocation.method(
          #signOut,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<_i2.AuthResult> signInWithGoogle() => (super.noSuchMethod(
        Invocation.method(
          #signInWithGoogle,
          [],
        ),
        returnValue: _i5.Future<_i2.AuthResult>.value(_FakeAuthResult_0(
          this,
          Invocation.method(
            #signInWithGoogle,
            [],
          ),
        )),
      ) as _i5.Future<_i2.AuthResult>);

  @override
  _i5.Future<void> updateProfile({
    String? firstName,
    String? lastName,
    String? profileImageUrl,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateProfile,
          [],
          {
            #firstName: firstName,
            #lastName: lastName,
            #profileImageUrl: profileImageUrl,
          },
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> updatePreferences(_i6.UserPreferences? preferences) =>
      (super.noSuchMethod(
        Invocation.method(
          #updatePreferences,
          [preferences],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> updateLanguageSettings({
    String? targetLanguage,
    String? nativeLanguage,
    String? supportLanguage1,
    String? supportLanguage2,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateLanguageSettings,
          [],
          {
            #targetLanguage: targetLanguage,
            #nativeLanguage: nativeLanguage,
            #supportLanguage1: supportLanguage1,
            #supportLanguage2: supportLanguage2,
          },
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> upgradeToPremium() => (super.noSuchMethod(
        Invocation.method(
          #upgradeToPremium,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<List<_i7.UserVocabularyItem>> getUserVocabulary(
          {String? language}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getUserVocabulary,
          [],
          {#language: language},
        ),
        returnValue: _i5.Future<List<_i7.UserVocabularyItem>>.value(
            <_i7.UserVocabularyItem>[]),
      ) as _i5.Future<List<_i7.UserVocabularyItem>>);

  @override
  _i5.Future<void> saveVocabularyItem(_i7.UserVocabularyItem? item) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveVocabularyItem,
          [item],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<_i7.UserVocabularyStats?> getUserVocabularyStats(
          String? language) =>
      (super.noSuchMethod(
        Invocation.method(
          #getUserVocabularyStats,
          [language],
        ),
        returnValue: _i5.Future<_i7.UserVocabularyStats?>.value(),
      ) as _i5.Future<_i7.UserVocabularyStats?>);

  @override
  _i5.Future<void> saveChatMessage(Map<String, dynamic>? message) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveChatMessage,
          [message],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<List<Map<String, dynamic>>> getChatHistory({int? limit = 50}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getChatHistory,
          [],
          {#limit: limit},
        ),
        returnValue: _i5.Future<List<Map<String, dynamic>>>.value(
            <Map<String, dynamic>>[]),
      ) as _i5.Future<List<Map<String, dynamic>>>);

  @override
  _i5.Future<_i3.FlashcardSession> createFlashcardSession(
          _i3.FlashcardSession? session) =>
      (super.noSuchMethod(
        Invocation.method(
          #createFlashcardSession,
          [session],
        ),
        returnValue:
            _i5.Future<_i3.FlashcardSession>.value(_FakeFlashcardSession_1(
          this,
          Invocation.method(
            #createFlashcardSession,
            [session],
          ),
        )),
      ) as _i5.Future<_i3.FlashcardSession>);

  @override
  _i5.Future<_i3.FlashcardSession?> getFlashcardSession(String? sessionId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getFlashcardSession,
          [sessionId],
        ),
        returnValue: _i5.Future<_i3.FlashcardSession?>.value(),
      ) as _i5.Future<_i3.FlashcardSession?>);

  @override
  _i5.Future<void> updateFlashcardSession(_i3.FlashcardSession? session) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateFlashcardSession,
          [session],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<List<_i3.FlashcardSession>> getUserFlashcardSessions(
          {int? limit = 50}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getUserFlashcardSessions,
          [],
          {#limit: limit},
        ),
        returnValue: _i5.Future<List<_i3.FlashcardSession>>.value(
            <_i3.FlashcardSession>[]),
      ) as _i5.Future<List<_i3.FlashcardSession>>);

  @override
  _i5.Future<void> deleteFlashcardSession(String? sessionId) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteFlashcardSession,
          [sessionId],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<_i3.FlashcardSessionCard> saveFlashcardSessionCard(
          _i3.FlashcardSessionCard? card) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveFlashcardSessionCard,
          [card],
        ),
        returnValue: _i5.Future<_i3.FlashcardSessionCard>.value(
            _FakeFlashcardSessionCard_2(
          this,
          Invocation.method(
            #saveFlashcardSessionCard,
            [card],
          ),
        )),
      ) as _i5.Future<_i3.FlashcardSessionCard>);

  @override
  _i5.Future<List<_i3.FlashcardSessionCard>> getSessionCards(
          String? sessionId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getSessionCards,
          [sessionId],
        ),
        returnValue: _i5.Future<List<_i3.FlashcardSessionCard>>.value(
            <_i3.FlashcardSessionCard>[]),
      ) as _i5.Future<List<_i3.FlashcardSessionCard>>);

  @override
  void clearError() => super.noSuchMethod(
        Invocation.method(
          #clearError,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addListener(_i8.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i8.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
