name: llm_chat_app
description: A Flutter chat application for web and iOS that integrates with LLM.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  http: ^1.1.0
  provider: ^6.0.5
  shared_preferences: ^2.2.0
  flutter_markdown: ^0.6.18
  flutter_dotenv: ^5.1.0
  google_generative_ai: ^0.2.0
  langchain: ^0.3.1+1
  langchain_openai: ^0.3.0
  langchain_google: ^0.2.2+1 
  ffi: ^2.1.0
  path_provider: ^2.1.2
  path: ^1.8.3
  yaml: ^3.1.2
  # User authentication and database
  sqflite: ^2.3.0
  crypto: ^3.0.3
  email_validator: ^2.1.17
  uuid: ^4.2.1
  # Supabase
  supabase_flutter: ^2.3.4
  # UI enhancements
  flutter_secure_storage: ^9.0.0
  shadcn_ui: ^0.26.5
  # JSON serialization
  json_annotation: ^4.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  json_serializable: ^6.7.1
  build_runner: ^2.4.7

flutter:
  uses-material-design: true
  assets:
    - .env
    - lib/config/prompt_config.yaml
    - lib/config/conversation_starters.yaml
    - assets/dictionaries/
    - lib/config/ 